---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: app
  labels:
    app: infra-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infra-app
      tier: memdatabase
  template:
    metadata:
      name: redis
      labels:
        app: infra-app
        tier: memdatabase
    spec:
      volumes:
        - name: redis-pv
          persistentVolumeClaim:
            claimName: redis-pvc
      containers:
        - name: redis
          image: redis:7.2.5-alpine
          args: ["--appendonly", "yes"]
          ports:
            - containerPort: 6379
          volumeMounts:
            - mountPath: "/data"
              name: redis-pv
