---
apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
data:
  rails_master_key: YzEyMmI3MzY4Mjc2MDhkYmE1MDU5OWY5Y2FhNTlhMTI=
  postgres_username: cG9zdGdyZXM=
  postgres_password: c2VjcmV0
